name: CI

# Triggers: Run on push to any branch and PRs to main
on:
  push:
    branches: ['**']  # All branches
  pull_request:
    branches: [main]

jobs:
  # Fast feedback job - runs on every push
  quick-check:
    name: Quick Check (Lint + Unit Tests)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm test -- --run

  # Build verification - ensures production build works
  build-check:
    name: Build Verification
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      - name: Check build output size
        run: |
          echo "Build completed successfully!"
          echo "Build artifacts:"
          ls -lh dist/ || echo "dist/ directory not found"

  # Optional: Type checking (if you want separate type check step)
  type-check:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript compiler check
        run: npx tsc --noEmit --skipLibCheck
